### ISSUE TITLE
call SNPs from thousands individuals

### ISSUE THREAD

**Issue by gorliver** [refresh-bio/SPLASH#18]
The concept is quick attracting. I wonder is it possible to call SNPs from a large population? If so, would you mind share the pipeline?

**Comment by roozbehdn** [comment]
Hi gorliver,

Yes, you can run SPLASH on datasets of anysize to obtain SNPs. One potential approach for identifying SNPs is to run the `SPLASH_extendor_classification.R` script from the repository and then looking at those anchors classified as `Base_pair_change_` (these are anchors whose target sequence diversity could be explain by single base pair changes (i.e., SNPs or mutations). The number after `_` gives you the number of base pairs that are different between the top two targets of the anchor. Hope this helps you.

**Comment by gorliver** [comment]
Sounds great! Definitely will try it.
