### ISSUE TITLE
OASIS test

### ISSUE THREAD

**Issue by xuyeluo** [refresh-bio/SPLASH#27]
Hi,
I read your paper [OASIS: An interpretable, finite-sample valid alternative to Pearson’s X2 for scientific discovery](https://www.pnas.org/doi/10.1073/pnas.2304671121) and was very interested in the OASIS test. It seems to be more efficient than the Pearson's chi-squared test. However, I cannot install the SPLASH program and run it. Then I tried to find the source code of the OASIS test and ran the test with some contingency tables. But I did not find the OASIS test function. 
Is there a simple code for the OASIS test? 
For example, just input the contingency table and then output the results(p-value, statistics, Effect Size, f ,c)?

**Comment by TavorB** [comment]
Thanks for your interest! I added a standalone python file and sample jupyter notebook with OASIS functionality here: https://github.com/refresh-bio/SPLASH/tree/master/OASIS . I'm looking into making OASIS pip installable, please let me know if you have any questions / comments.

**Comment by xuyeluo** [comment]
Thank you!
