### ISSUE TITLE
Download page missing?

### ISSUE THREAD

**Issue by joegeorgeson** [refresh-bio/SPLASH#33]
Hi SPLASH,

It looks like the url listed in the download.py isn't there anymore;
https://raw.githubusercontent.com/salzman-lab/nomad/main/test_data/

Is the below the same?
https://github.com/salzman-lab/SPLASH/tree/main/test_data

**Comment by marekkokot** [comment]
Hi,

thank you.
Yes, the below is the same, but I just checked, and it seems that links generated by download.py are fine.
And download.py works and downloads the data.
Just in case, here are the generated URLs:
https://raw.githubusercontent.com/salzman-lab/nomad/main/test_data/SRX14565338_SRR18431620_1.fastq.gz
https://raw.githubusercontent.com/salzman-lab/nomad/main/test_data/SRX14565342_SRR18431616_1.fastq.gz
https://raw.githubusercontent.com/salzman-lab/nomad/main/test_data/SRX14565346_SRR18431612_1.fastq.gz
https://raw.githubusercontent.com/salzman-lab/nomad/main/test_data/SRX14565361_SRR18431597_1.fastq.gz

so I don't think there is a need to change anything. Have you had any issues running download.py?

**Comment by joegeorgeson** [comment]
Ya thanks, i see it was a permission issue of the node...
