### ISSUE TITLE
Issue on the option run_10X

### ISSUE THREAD

**Issue by chstellar** [refresh-bio/SPLASH#8]
Hi, I've been trying to run SPLASH on paired-end data, but none of `--run_10X`, `-run_10X`, or `run_10X` was recognised as a valid argument by SPLASH. I can see the option 'run_10X' in the documentation, but I am not sure how is this option involved in SPLASH by reading the source code. 
Also, I have read the documentation and source code, but I did not get an idea of how should I specify the input file when running in 10X mode. 
My command line instruction was `../splash --bin_path .. input.txt` which ran without an error and yielded desired results. Could you provide some hints on how should I adjust my input to allow SPLASH to run in 10X mode? Many thanks.

**Comment by marekkokot** [comment]
Hi, thank you!
I think our README is more updated than it should be.
We have in fact a version supporting 10X, but it's not yet publicly available - we are still making some improvements and testing before publishing.

**Comment by chstellar** [comment]
Thanks for your efforts and looking forward to the updated version :)

**Comment by lcmmichielsen** [comment]
Hi! I'm interested in the 10x version of the package as well. Do you have any idea when it will become available?

**Comment by roozbehdn** [comment]
Hi @lcmmichielsen, thanks for your interest in running SPLASH on 10x, we are working on 10x pipeline currently and hope to release it within the next few weeks. We will update this repo when it becomes available.
