### ISSUE TITLE
GRCh38 / Gencode annotation files

### ISSUE THREAD

**Issue by tomsing1** [refresh-bio/SPLASH#9]
Thanks a lot for making the Human (T2T) annotation files available for download. There is a lot of data out that has been analyzed using GRCh38, e.g. with Gencode annotations. Perhaps you might consider providing additional annotation files for that genome release? (Or maybe it is obvious how to generate those files? At first glance, I couldn't find information on how to make my own. Perhaps I missed it?)

**Comment by roozbehdn** [comment]
Hi @tomsing1, annotation files based on hg38 are now available and can be downloaded from the links provided in the repo (https://github.com/refresh-bio/SPLASH/blob/master/README.md#annotation-files-for-human-and-mouse). You also need to have STAR and bowtie index files for hg38 assembly from ncbi refseq.

**Comment by tomsing1** [comment]
Thank you so much!
